"""posts table

Revision ID: 64698878223d
Revises: 86d60f96cb5a
Create Date: 2022-11-16 10:07:33.266996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64698878223d'
down_revision = '86d60f96cb5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('dislikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'dislikes')
    op.drop_column('posts', 'likes')
    op.drop_column('posts', 'views')
    # ### end Alembic commands ###
