"""remove extra fields from posts table

Revision ID: 75a421ec1ac2
Revises: f58da2e6a970
Create Date: 2022-11-17 21:57:18.249013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a421ec1ac2'
down_revision = 'f58da2e6a970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'likes')
    op.drop_column('posts', 'dislikes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('dislikes', sa.INTEGER(), nullable=True))
    op.add_column('posts', sa.Column('likes', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
