"""add main image to posts table

Revision ID: 920fd041f98c
Revises: 75a421ec1ac2
Create Date: 2022-11-20 14:19:18.951918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920fd041f98c'
down_revision = '75a421ec1ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('preview_img', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('main_img', sa.String(), nullable=False))
    op.drop_column('posts', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('img', sa.VARCHAR(), nullable=False))
    op.drop_column('posts', 'main_img')
    op.drop_column('posts', 'preview_img')
    # ### end Alembic commands ###
